### ISSUE TITLE
Running bootstrap-iso on Kali with a Kali image gives an error before finishing

### ISSUE THREAD

**Issue by antichamber** [cawilliamson/ansible-gpdpocket#12] opened 2017-08-07 17:40 UTC
After getting around the space in removable volume error by renaming my removable volume and trying again, I'm greeted by this Error https://imgur.com/a/2ULjx

**Comment by cawilliamson** [comment] 2017-08-07 18:12
This is a duplicate of:

https://github.com/cawilliamson/ansible-gpdpocket/issues/9

I believe this issue should now be fixed. Please give it a try and let me know on issue #9 if not.

**Closed by cawilliamson** 2017-08-07 18:12 UTC
