### ISSUE TITLE
Manjaro doesn't ISO bootstrap properly

### ISSUE THREAD

**Issue by LeosDing** [cawilliamson/ansible-gpdpocket#41] opened 2017-08-12 05:20 UTC
`125 dd if="${1}" bs=512 count=1 of=${TMPDIR}/isolinux/isohdpfx.bin`

Manjaro iso didn't have isolinux directory, so when bootstrap-iso.sh execute that line, will error.

**Comment by LeosDing** [comment] 2017-08-12 05:43
manjaro-i3 iso using grub2 loading kernel.

**Comment by cawilliamson** [comment] 2017-08-12 07:13
I'm quite tempted to drop support for manjaro to be honest - it has cost me literally days of time to support it over any other distro. Maybe the devs could quit doing weird things and make my life a lot easier. :|

I'll have a look and see what I can do.

**Comment by LeosDing** [comment] 2017-08-12 10:39
@cawilliamson manjaro-i3-17.0.2-stable-x86_64.iso is not contains isolinux, so when bootstrap-iso.sh execute next command will cause error.

`128 xorriso -as mkisofs -iso-level 3 -full-iso9660-filenames -volid "${ISO_LABEL}" \
129     -eltorito-boot isolinux/isolinux.bin -eltorito-catalog isolinux/boot.cat \
130     -no-emul-boot -boot-load-size 4 -boot-info-table -isohybrid-mbr ${TMPDIR}/isolinux/isohdpfx.bin \
131     -eltorito-alt-boot -e $(sed "s,${TMPDIR}/,," - <<< ${EFI_PATH}) -no-emul-boot -isohybrid-gpt-basdat \
132     -output ${HOME}/bootstrap.iso ${TMPDIR}`

**Comment by LeosDing** [comment] 2017-08-12 10:48
`
+ dd if=manjaro-i3-17.0.2-stable-x86_64.iso bs=512 count=1 of=/var/tmp/bootstrap-iso/isolinux/isohdpfx.bin
dd: failed to open '/var/tmp/bootstrap-iso/isolinux/isohdpfx.bin': No such file or directory
`

**Comment by cawilliamson** [comment] 2017-08-12 10:59
Got it - thanks @LeosDing - as I said in my previous post - leave it with me and I'll look in to it and try and get it fixed.

Really getting tired of Manjaro though - it seems to follow absolutely no standards whatsoever.

**Comment by snazzybunny** [comment] 2017-08-14 05:52
If Manjaro isn't working properly, I can confirm that the Antergos iso seems to build fine.

**Comment by LeosDing** [comment] 2017-08-15 11:08
@cawilliamson new rebuild error log

`TASK [iso : copy bootstrap-system script to guest] *******************************************************************************
changed: [localhost]

TASK [iso : bootstrap guest (this may take a while)] *****************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "chroot /var/tmp/bootstrap-iso/squashfs /bin/bash -c \"/bin/bash /tmp/bootstrap-system.sh\"", "delta": "1:39:24.765231", "end": "2017-08-15 16:38:54.812386", "failed": true, "rc": 128, "start": "2017-08-15 14:59:30.047155", "stderr": "+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n++ stat -c %d:%i /\n++ stat -c %d:%i /proc/1/root/.\n+ '[' 2085:4723177 == 2085:2 ']'\n+ ping -c1 8.8.8.8\n+ '[' -f /usr/bin/pacman ']'\n+ pacman-key --init\n+ pacman-key --populate archlinux\ngpg: next trustdb check due at 2017-10-20\n+ pacman -Sy --noconfirm ansible git\nerror: failed retrieving file 'extra.db' from manjaro.mirror.wearetriple.com : transfer closed with 1714696 bytes remaining to read\nerror: failed retrieving file 'community.db' from manjaro.mirror.wearetriple.com : Resolving timed out after 10519 milliseconds\nerror: failed retrieving file 'community.db' from manjaro.cu.be : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds\nerror: failed retrieving file 'community.db' from ct.mirror.garr.it : OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104\nerror: failed retrieving file 'community.db' from mirror.yandex.ru : Resolving timed out after 10519 milliseconds\nerror: failed retrieving file 'python2-2.7.13-4-x86_64.pkg.tar.xz' from manjaro.mirror.wearetriple.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds\nerror: failed retrieving file 'git-2.13.4-1-x86_64.pkg.tar.xz' from manjaro.mirror.wearetriple.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds\n+ rm -rf /usr/src/ansible-gpdpocket\n+ git clone --depth 1 https://github.com/cawilliamson/ansible-gpdpocket.git /usr/src/ansible-gpdpocket\nCloning into '/usr/src/ansible-gpdpocket'...\nerror: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104\nfatal: The remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed", "stderr_lines": ["+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "++ stat -c %d:%i /", "++ stat -c %d:%i /proc/1/root/.", "+ '[' 2085:4723177 == 2085:2 ']'", "+ ping -c1 8.8.8.8", "+ '[' -f /usr/bin/pacman ']'", "+ pacman-key --init", "+ pacman-key --populate archlinux", "gpg: next trustdb check due at 2017-10-20", "+ pacman -Sy --noconfirm ansible git", "error: failed retrieving file 'extra.db' from manjaro.mirror.wearetriple.com : transfer closed with 1714696 bytes remaining to read", "error: failed retrieving file 'community.db' from manjaro.mirror.wearetriple.com : Resolving timed out after 10519 milliseconds", "error: failed retrieving file 'community.db' from manjaro.cu.be : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds", "error: failed retrieving file 'community.db' from ct.mirror.garr.it : OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104", "error: failed retrieving file 'community.db' from mirror.yandex.ru : Resolving timed out after 10519 milliseconds", "error: failed retrieving file 'python2-2.7.13-4-x86_64.pkg.tar.xz' from manjaro.mirror.wearetriple.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds", "error: failed retrieving file 'git-2.13.4-1-x86_64.pkg.tar.xz' from manjaro.mirror.wearetriple.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds", "+ rm -rf /usr/src/ansible-gpdpocket", "+ git clone --depth 1 https://github.com/cawilliamson/ansible-gpdpocket.git /usr/src/ansible-gpdpocket", "Cloning into '/usr/src/ansible-gpdpocket'...", "error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104", "fatal: The remote end hung up unexpectedly", "fatal: early EOF", "fatal: index-pack failed"], "stdout": "==> Appending keys from archlinux.gpg...\n==> Locally signing trusted keys in keyring...\n  -> Locally signing key DDB867B92AA789C165EEFA799B729B06A680C281...\n  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...\n  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...\n  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...\n  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...\n  -> Locally signing key 44D4A033AC140143927397D47EFD567D4C7EA887...\n==> Importing owner trust values...\n==> Disabling revoked keys in keyring...\n  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...\n  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...\n  -> Disabling key 40440DC037C05620984379A6761FAD69BA06C6A9...\n  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...\n  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...\n  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...\n  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...\n  -> Disabling key 5E7585ADFF106BFFBBA319DC654B877A0864983E...\n  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...\n  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...\n  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...\n  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...\n  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...\n  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...\n  -> Disabling key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...\n==> Updating trust database...\n:: Synchronizing package databases...\ndownloading core.db...\ndownloading extra.db...\ndownloading extra.db...\ndownloading community.db...\ndownloading community.db...\ndownloading community.db...\ndownloading multilib.db...\nresolving dependencies...\nlooking for conflicting packages...\n\nPackages (27) libsodium-1.0.13-1  libyaml-0.1.7-1  perl-error-0.17024-2  python2-2.7.13-4  python2-appdirs-1.4.3-1  python2-asn1crypto-0.22.0-1  python2-bcrypt-3.1.3-1  python2-cffi-1.10.0-1  python2-crypto-2.6.1-5  python2-cryptography-2.0.3-1  python2-enum34-1.1.6-1  python2-idna-2.5-1  python2-ipaddress-1.0.18-1  python2-jinja-2.9.6-1  python2-markupsafe-1.0-1  python2-packaging-16.8-2  python2-paramiko-2.2.1-1  python2-ply-3.10-1  python2-pyasn1-0.3.1-1  python2-pycparser-2.18-1  python2-pynacl-1.1.2-1  python2-pyparsing-2.2.0-1  python2-setuptools-1:36.2.7-1  python2-six-1.10.0-3  python2-yaml-3.12-2  ansible-2.3.1.0-1  git-2.13.4-1\n\nTotal Download Size:    23.03 MiB\nTotal Installed Size:  164.75 MiB\n\n:: Proceed with installation? [Y/n] \n:: Retrieving packages...\ndownloading python2-2.7.13-4-x86_64.pkg.tar.xz...\ndownloading libyaml-0.1.7-1-x86_64.pkg.tar.xz...\ndownloading python2-ply-3.10-1-any.pkg.tar.xz...\ndownloading python2-pycparser-2.18-1-any.pkg.tar.xz...\ndownloading python2-cffi-1.10.0-1-x86_64.pkg.tar.xz...\ndownloading python2-six-1.10.0-3-any.pkg.tar.xz...\ndownloading python2-idna-2.5-1-any.pkg.tar.xz...\ndownloading python2-ipaddress-1.0.18-1-any.pkg.tar.xz...\ndownloading python2-pyparsing-2.2.0-1-any.pkg.tar.xz...\ndownloading python2-packaging-16.8-2-any.pkg.tar.xz...\ndownloading python2-appdirs-1.4.3-1-any.pkg.tar.xz...\ndownloading python2-setuptools-1:36.2.7-1-any.pkg.tar.xz...\ndownloading python2-asn1crypto-0.22.0-1-any.pkg.tar.xz...\ndownloading python2-cryptography-2.0.3-1-x86_64.pkg.tar.xz...\ndownloading python2-pyasn1-0.3.1-1-any.pkg.tar.xz...\ndownloading python2-markupsafe-1.0-1-x86_64.pkg.tar.xz...\ndownloading python2-crypto-2.6.1-5-x86_64.pkg.tar.xz...\ndownloading perl-error-0.17024-2-any.pkg.tar.xz...\ndownloading git-2.13.4-1-x86_64.pkg.tar.xz...\ndownloading python2-yaml-3.12-2-x86_64.pkg.tar.xz...\ndownloading python2-bcrypt-3.1.3-1-x86_64.pkg.tar.xz...\ndownloading python2-enum34-1.1.6-1-any.pkg.tar.xz...\ndownloading libsodium-1.0.13-1-x86_64.pkg.tar.xz...\ndownloading python2-pynacl-1.1.2-1-x86_64.pkg.tar.xz...\ndownloading python2-paramiko-2.2.1-1-any.pkg.tar.xz...\ndownloading python2-jinja-2.9.6-1-any.pkg.tar.xz...\ndownloading ansible-2.3.1.0-1-any.pkg.tar.xz...\nchecking keyring...\nchecking package integrity...\nloading package files...\nchecking for file conflicts...\nchecking available disk space...\n:: Processing package changes...\ninstalling python2...\nOptional dependencies for python2\n    tk: for IDLE\n    python2-setuptools [pending]\n    python2-pip\ninstalling libyaml...\ninstalling python2-yaml...\n==> Note that even though this package uses libyaml library,\n==> slower pure python implementation is used by default.\n==> See http://pyyaml.org/wiki/PyYAMLDocumentation\ninstalling python2-ply...\ninstalling python2-pycparser...\ninstalling python2-cffi...\ninstalling python2-six...\ninstalling python2-bcrypt...\ninstalling python2-enum34...\ninstalling python2-idna...\ninstalling python2-ipaddress...\ninstalling python2-pyparsing...\ninstalling python2-packaging...\ninstalling python2-appdirs...\ninstalling python2-setuptools...\ninstalling python2-asn1crypto...\ninstalling python2-cryptography...\ninstalling python2-pyasn1...\ninstalling libsodium...\ninstalling python2-pynacl...\ninstalling python2-paramiko...\ninstalling python2-markupsafe...\ninstalling python2-jinja...\ninstalling python2-crypto...\ninstalling ansible...\nOptional dependencies for ansible\n    sshpass: for ssh connections with password\n    python2-passlib: crypt values for vars_prompt\n    python2-netaddr: for the ipaddr filter\n    python2-systemd: log to journal\n    python2-pywinrm: connect to Windows machines\n    python2-ovirt-engine-sdk: ovirt support\n    python2-jmespath: json_query support\ninstalling perl-error...\ninstalling git...\nOptional dependencies for git\n    tk: gitk and git gui\n    perl-libwww: git svn\n    perl-term-readkey: git svn\n    perl-mime-tools: git send-email\n    perl-net-smtp-ssl: git send-email TLS support\n    perl-authen-sasl: git send-email TLS support\n    perl-mediawiki-api: git mediawiki support\n    perl-datetime-format-iso8601: git mediawiki support\n    perl-lwp-protocol-https: git mediawiki https support\n    python2: various helper scripts [installed]\n    subversion: git svn\n    cvsps2: git cvsimport\n    gnome-keyring: GNOME keyring credential helper\n:: Running post-transaction hooks...\n(1/1) Arming ConditionNeedsUpdate...", "stdout_lines": ["==> Appending keys from archlinux.gpg...", "==> Locally signing trusted keys in keyring...", "  -> Locally signing key DDB867B92AA789C165EEFA799B729B06A680C281...", "  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...", "  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...", "  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...", "  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...", "  -> Locally signing key 44D4A033AC140143927397D47EFD567D4C7EA887...", "==> Importing owner trust values...", "==> Disabling revoked keys in keyring...", "  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...", "  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...", "  -> Disabling key 40440DC037C05620984379A6761FAD69BA06C6A9...", "  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...", "  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...", "  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...", "  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...", "  -> Disabling key 5E7585ADFF106BFFBBA319DC654B877A0864983E...", "  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...", "  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...", "  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...", "  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...", "  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...", "  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...", "  -> Disabling key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...", "==> Updating trust database...", ":: Synchronizing package databases...", "downloading core.db...", "downloading extra.db...", "downloading extra.db...", "downloading community.db...", "downloading community.db...", "downloading community.db...", "downloading multilib.db...", "resolving dependencies...", "looking for conflicting packages...", "", "Packages (27) libsodium-1.0.13-1  libyaml-0.1.7-1  perl-error-0.17024-2  python2-2.7.13-4  python2-appdirs-1.4.3-1  python2-asn1crypto-0.22.0-1  python2-bcrypt-3.1.3-1  python2-cffi-1.10.0-1  python2-crypto-2.6.1-5  python2-cryptography-2.0.3-1  python2-enum34-1.1.6-1  python2-idna-2.5-1  python2-ipaddress-1.0.18-1  python2-jinja-2.9.6-1  python2-markupsafe-1.0-1  python2-packaging-16.8-2  python2-paramiko-2.2.1-1  python2-ply-3.10-1  python2-pyasn1-0.3.1-1  python2-pycparser-2.18-1  python2-pynacl-1.1.2-1  python2-pyparsing-2.2.0-1  python2-setuptools-1:36.2.7-1  python2-six-1.10.0-3  python2-yaml-3.12-2  ansible-2.3.1.0-1  git-2.13.4-1", "", "Total Download Size:    23.03 MiB", "Total Installed Size:  164.75 MiB", "", ":: Proceed with installation? [Y/n] ", ":: Retrieving packages...", "downloading python2-2.7.13-4-x86_64.pkg.tar.xz...", "downloading libyaml-0.1.7-1-x86_64.pkg.tar.xz...", "downloading python2-ply-3.10-1-any.pkg.tar.xz...", "downloading python2-pycparser-2.18-1-any.pkg.tar.xz...", "downloading python2-cffi-1.10.0-1-x86_64.pkg.tar.xz...", "downloading python2-six-1.10.0-3-any.pkg.tar.xz...", "downloading python2-idna-2.5-1-any.pkg.tar.xz...", "downloading python2-ipaddress-1.0.18-1-any.pkg.tar.xz...", "downloading python2-pyparsing-2.2.0-1-any.pkg.tar.xz...", "downloading python2-packaging-16.8-2-any.pkg.tar.xz...", "downloading python2-appdirs-1.4.3-1-any.pkg.tar.xz...", "downloading python2-setuptools-1:36.2.7-1-any.pkg.tar.xz...", "downloading python2-asn1crypto-0.22.0-1-any.pkg.tar.xz...", "downloading python2-cryptography-2.0.3-1-x86_64.pkg.tar.xz...", "downloading python2-pyasn1-0.3.1-1-any.pkg.tar.xz...", "downloading python2-markupsafe-1.0-1-x86_64.pkg.tar.xz...", "downloading python2-crypto-2.6.1-5-x86_64.pkg.tar.xz...", "downloading perl-error-0.17024-2-any.pkg.tar.xz...", "downloading git-2.13.4-1-x86_64.pkg.tar.xz...", "downloading python2-yaml-3.12-2-x86_64.pkg.tar.xz...", "downloading python2-bcrypt-3.1.3-1-x86_64.pkg.tar.xz...", "downloading python2-enum34-1.1.6-1-any.pkg.tar.xz...", "downloading libsodium-1.0.13-1-x86_64.pkg.tar.xz...", "downloading python2-pynacl-1.1.2-1-x86_64.pkg.tar.xz...", "downloading python2-paramiko-2.2.1-1-any.pkg.tar.xz...", "downloading python2-jinja-2.9.6-1-any.pkg.tar.xz...", "downloading ansible-2.3.1.0-1-any.pkg.tar.xz...", "checking keyring...", "checking package integrity...", "loading package files...", "checking for file conflicts...", "checking available disk space...", ":: Processing package changes...", "installing python2...", "Optional dependencies for python2", "    tk: for IDLE", "    python2-setuptools [pending]", "    python2-pip", "installing libyaml...", "installing python2-yaml...", "==> Note that even though this package uses libyaml library,", "==> slower pure python implementation is used by default.", "==> See http://pyyaml.org/wiki/PyYAMLDocumentation", "installing python2-ply...", "installing python2-pycparser...", "installing python2-cffi...", "installing python2-six...", "installing python2-bcrypt...", "installing python2-enum34...", "installing python2-idna...", "installing python2-ipaddress...", "installing python2-pyparsing...", "installing python2-packaging...", "installing python2-appdirs...", "installing python2-setuptools...", "installing python2-asn1crypto...", "installing python2-cryptography...", "installing python2-pyasn1...", "installing libsodium...", "installing python2-pynacl...", "installing python2-paramiko...", "installing python2-markupsafe...", "installing python2-jinja...", "installing python2-crypto...", "installing ansible...", "Optional dependencies for ansible", "    sshpass: for ssh connections with password", "    python2-passlib: crypt values for vars_prompt", "    python2-netaddr: for the ipaddr filter", "    python2-systemd: log to journal", "    python2-pywinrm: connect to Windows machines", "    python2-ovirt-engine-sdk: ovirt support", "    python2-jmespath: json_query support", "installing perl-error...", "installing git...", "Optional dependencies for git", "    tk: gitk and git gui", "    perl-libwww: git svn", "    perl-term-readkey: git svn", "    perl-mime-tools: git send-email", "    perl-net-smtp-ssl: git send-email TLS support", "    perl-authen-sasl: git send-email TLS support", "    perl-mediawiki-api: git mediawiki support", "    perl-datetime-format-iso8601: git mediawiki support", "    perl-lwp-protocol-https: git mediawiki https support", "    python2: various helper scripts [installed]", "    subversion: git svn", "    cvsps2: git cvsimport", "    gnome-keyring: GNOME keyring credential helper", ":: Running post-transaction hooks...", "(1/1) Arming ConditionNeedsUpdate..."]}
	to retry, use: --limit @/home/catlog/Study/gpd/ansible-gpdpocket/iso.retry

PLAY RECAP ***********************************************************************************************************************
localhost                  : ok=19   changed=10   unreachable=0    failed=1   
`

**Comment by cawilliamson** [comment] 2017-08-18 19:07
@LeosDing "Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds" - are you trying to bootstrap from behind a proxy? That will not work.

**Comment by cawilliamson** [comment] 2017-08-19 15:40
This has taken FAR more work than I was intending to spend on it but it looks like the ISO bootstrap now succeeds.

I'm going to close this off for now but if you face further issues with actually using the produced ISO please raise another issue.

Thanks!

**Closed by cawilliamson** 2017-08-19 15:40 UTC
Labels: bug
