### ISSUE TITLE
System freezes under load (linux mint)

### ISSUE THREAD

**Issue by fishkopf** [cawilliamson/ansible-gpdpocket#33] opened 2017-08-10 18:04 UTC
Hey,
So i already had this problem with the respin approach, when the system is under load (like building hans' kernel, or watching full HD youtube) the system freezes completely. Since so many of you seems to have no problem, my guess was that it was a hardware issue, but under Windows I don't have any problems, even gaming is no issue. So even though I cannot rule out a hardware issue I don't think it is one.
What i know:

- It seems to have nothing to do with any graphics since i get can reproduce the problem without the display server started
- Not Bios related, i tried all Bios version I could find (standard configuration)
- Unlikely to be network related (i shut that off).
- Obviously only on high load.
- does seem to happen on multiple versions of the kernel: the standard respin kernel, this standard kernel and the 4.13.0-rc3 i build.
With one BIOS version, i got a little bit of output in the terminal

> INFO: rcu_sched detected stalls in CPUs/tasks:
>$0-...: (0 ticks this GP) idle=328/0/0 softirq=411102/411102 fqs=0
>$3-... (117 GPs behind) idle=064/0/0 softirq=497198/497199 fqs=0
>$(detected by 1, t=60002 jifffies, g=238927, c=238926, q=1087)
>watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [kworker/2:0:8085]
>rcu_sched kthread starved for 60002 jiffies! g248927 c238926 f0x0 RCU_GP_WAIT_FQS(3) -> state=0x1
>watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [kworker/2:0:8085]
>watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [kworker/2:0:8085]
>INFO: rcu_sched self-detected stall on CPU
>INFO: rcu_sched detected stalls on CPUs/tasks:
>$2-...: (59998 thicks this GP) idle=696/140000000000001/0 softirq=466046/466046 fqs=14999
>$(detected by 1, t=60002 jiffies, g=238928, c=238927,q=1156)
>$2-...: (59998 thicks this GP) idle=696/140000000000001/0 softirq=466046/466046 fqs=15001
>$(detected by 1, t=60002 jiffies, g=238927, c=238927,q=1156)
>watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [kworker/2:0:8085]
>watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [kworker/2:0:8085]

My guess is this is a kernel bug.
Could be Ubuntu related, i haven't tired any other distribution so far. 
And since most of you seems to not have this problem, i guess it could be related to different versions of the GPD Pocket?
So I got mine just about 1,5 weeks ago from a reseller, so probably i have a "new" versions, and a lot of you don't have the problem, because they have the "first" version, from the Kickstarter campaign? 
I guess i have to raise this to Hans, but I cannot post an issue on his github.

Happy to provide any futher information i can find

**Comment by vicentegomez** [comment] 2017-08-10 18:22
I'm having this same issue on Mint 18.2.

**Comment by cawilliamson** [comment] 2017-08-10 18:42
Ok two things:

1.) Could you tell me what the result of the following command is?

    systemctl status gpd-fan

2.) You will want to ensure you are running the latest BIOS:

https://github.com/stockmind/gpd-pocket-ubuntu-respin#bios-updates-and-original-firmwares

A combination of the two has completely resolved any and ALL freezing issues for me although typically the gpd-fan script working was enough to avoid reaching the trigger temperatures for the old BIOS. The new BIOS has much higher temps before crashing (completely safe - GPD set the initial crash temps FAR too low - like 30 degrees before it would even be a problem.)

**Comment by fishkopf** [comment] 2017-08-10 19:45
I just installed the 07/05/2017 BIOS (again) and it seems like it actually takes longer (about 7 minutes of compiling while charging) till the freeze occurs, but it happens GPD is running ofc.

> gpd-fan.service - GPD Fan Daemon
> Loaded: loaded (/etc/systemd/gpd-fan.service; eabled; vandor preset: enabled)
>Acitve: active (running) since Do 2017-08-10 20:51:12 CEST: 1min 45s ago
>Main PID: 788 (python 2.7)
>CGroup: /system.slice/gpd-fan.service
>             - 788 python2.7 /usr/local/sbin/gpd-fan --time=10 --turbo=60 --min=40 --med=50 --max=60

**Comment by cawilliamson** [comment] 2017-08-10 21:51
I have seen that 68 degrees C causes these systems to instantly stall and typically I have avoided this happening (using the gpd-fan script) by disabling turbo boost (in your case, at 60 degrees C.) It's crazy that you're still reaching those high temps - I haven't had a crash for weeks.

It's a very strange one and not really in the scope of this project *but* the advice I would try is following this:

https://www.reddit.com/r/GPDPocket/comments/6s7zck/my_unlocked_bios_working_settings_dptf_limit/

Using the "Ubuntu BIOS" - unlocked one ( available at https://www.reddit.com/r/GPDPocket/comments/6q74en/unlocked_gpd_pocket_bios/ ) you can change the settings listed above.

Another less invasive (but also likely less relevant) option is to add the following to your boot options:

`i915.semaphores=1`

**Comment by fishkopf** [comment] 2017-08-11 20:06
Well, that was helpful. The whole time I was wondering why it the freezes happens on my part like all the time, reproducible and no one else had any issues, now I am learning that you used a hardware mod on your GPD. Was thinking about doing a hardware mod on my GPD as well, but didn't want to start yet because i couldn't rule out, that the issue was a hardware failure, and creating a hardware mod could make it harder to return the unit.
I think something like that would be great as a side-note in the README  or at least in the Reddit post.
So Ill get myself some thermal pad next week and a heat pipe, and will mod my gpd. 
 

>I have seen that 68 degrees C causes these systems to instantly stall and typically I have avoided this happening (using the gpd-fan script) by disabling turbo boost (in your case, at 60 degrees C.)

Sorry English is not my mother tongue (obviously). What exactly do you mean with that sentence, can you actually disable the turbo boost (at a certain temperature) using the gpd-fan script? if so, could you point me to website or README where i can learn more about it?

PS: the 77 degree C, where a stress test, therefore the point was to get the temperature as high as possible, it is not always at that temperature ;)

Thanks for your answer it really helped me a lot.

**Comment by cawilliamson** [comment] 2017-08-11 21:20
Wait a sec - I did perform those hardware mods but it wasn't to stop the crashing issue - that was resolved months ago for me with the fan control script stuff. I haven't had a crash for a long while and also - if you're getting crashes in Linux but not Windows - it's not a hardware problem but a software one.

When the system crashes - are you able to find out if turbo boost is enabled?

`watch -n1 cat /sys/devices/system/cpu/intel_pstate/no_turbo`

**Comment by vicentegomez** [comment] 2017-08-11 21:22
I've installed Ubuntu 17.04 and so far it's stable. Windows is stable. 
It seems to be a Mint 18.2 issue for me.

**Comment by cawilliamson** [comment] 2017-08-11 21:24
Hm, that's very odd.

I'm running Linux Mint at the minute but I did run Mint for a while - though I didn't really push it hard.

I think the kernel compiling it what's bringing the crashing to the attention of people because it stresses the CPUs. My only theory though is that turbo mode isn't turning off at high temps properly - may add logging to that - then at least we can get some debugging output from it.

**Comment by vicentegomez** [comment] 2017-08-11 21:31
The way I can quickly reproduce a crash in Mint 18.2 is when watching a 1080p h.264 YouTube video (using the h264ify extension). After a few minutes it will crash. When exiting full screen it will almost always crash.

**Comment by cawilliamson** [comment] 2017-08-12 10:18
Yet the same doesn't happen on Ubuntu following the same instructions?

**Comment by vicentegomez** [comment] 2017-08-12 20:46
I installed Ubuntu 16.04 and it crashes too.

Reinstalled Ubuntu 17.04 and it doesn't crash.

**Comment by cawilliamson** [comment] 2017-08-12 21:25
I'm marking this WONTFIX for now because I don't believe this is an issue with the ansible config but rather either with the kernel or your BIOS settings perhaps.

I'll leave the ticket open, however, for further discussion in case anyone has any ideas on how to fix this.

**Comment by cawilliamson** [comment] 2017-08-13 22:55
I'll have a think about this one - it's very odd that Ubuntu 16.04 and Mint 18.2 both crash (and are both based on Ubuntu 16.04) but no other distros seem to.

I did run Ubuntu 16.04 myself for a while too - didn't face any crashing problems once i had the gpd-fan stuff figured out (i.e. disabling turbo boost at high temps.)

If someone fancies experimenting - could you try the following BIOS settings (you'll need the "ubuntu" unlocked BIOS):

https://www.reddit.com/r/GPDPocket/comments/6s7zck/my_unlocked_bios_working_settings_dptf_limit/

I'm curious to know if any of the settings here prevent this crash - I'm wondering if perhaps tlp is causing the instability. You could try disabling tlp too and see if that helps.

**Closed** 2017-08-18 14:16 UTC
Labels: wontfix
