### ISSUE TITLE
Wrong vmlinuz image name in grub, no initrd file

### ISSUE THREAD

**Issue by Sonique** [cawilliamson/ansible-gpdpocket#80] opened 2017-08-19 12:02 UTC
1) Grub can't find 4.13 kernel image, because file name is incorrect
2) initrd image did not appear in /boot/ folder after gpd-pocket update

I changed vmlinuz image name in grub, and then found that initrd.img for 4.13 doesn't exists.
I think, maybe deleting old image not good idea, because now I should reinstall linux again, with previous kernel image it will be simpler and quicker. Maybe better to rename it.

![photo 19-08-2017 14 47 42](https://user-images.githubusercontent.com/662904/29486469-ced07aca-84ee-11e7-9a93-1f98499c30ad.jpg)
![photo 19-08-2017 14 19 38](https://user-images.githubusercontent.com/662904/29486467-ceb1f3b6-84ee-11e7-8c98-2cff631b572a.jpg)
![photo 19-08-2017 14 22 40](https://user-images.githubusercontent.com/662904/29486468-ceb2f1da-84ee-11e7-885b-63dccc7a3f71.jpg)
![photo 19-08-2017 14 26 36](https://user-images.githubusercontent.com/662904/29486470-ced08a60-84ee-11e7-9a66-2d810a74cc0b.jpg)

**Comment by cawilliamson** [comment] 2017-08-19 13:06
You could boot the generic images to get back in to your system (just run them with `nomodeset fbcon=rotate:1` - should at least get you booting up.

I'll look in to what caused this - others have reported this change resolved issues - not caused them.

**Comment by cawilliamson** [comment] 2017-08-19 13:37
I've added a fix for this not being detected before you rebooted but I still don't understand the root cause here.

Once you've got a bootable system - could you remove `rm -rf /usr/src/linux-jwrdegoede` and then `sudo gpd-update` again, then before rebooting provide the output from this command? That way I should be able to find out what went wrong since the ansible playbook should have failed to complete if there are any problems present at that point.

**Comment by Sonique** [comment] 2017-08-19 17:04
I try to install again, firstly I get your ubuntu image. Then I run bootstrap script on it And get eror with initramfs-tools. I not run update yet, but I think maybe it's on of the reasons.

![photo 19-08-2017 19 53 56](https://user-images.githubusercontent.com/662904/29488723-93c2c124-8519-11e7-9950-5d9138d4dee2.jpg)

**Comment by cawilliamson** [comment] 2017-08-19 20:37
I've added an experimental fix for this - feel free to give it a shot and let me know how it turns out. :)

**Comment by cawilliamson** [comment] 2017-08-20 23:30
I'm closing this ticket in favour of #82 since there has been a lot of working happening to resolve this issue over there.

**Closed by cawilliamson** 2017-08-20 23:30 UTC
Labels: bug
