### ISSUE TITLE
Syntax Error while loading YAML

### ISSUE THREAD

**Issue by lucasdurand** [cawilliamson/ansible-gpdpocket#98] opened 2017-08-22 04:21 UTC
First off, thanks for all the effort going into this, very promising. 

Issue: Trying to bootstrap an Ubuntu-16.04.3 iso from within an existing Ubuntu instance. Running into an error, which appears to be when Ansible starts getting involved. Very possible I'm doing something wrong.

```
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
+ grep -wq -- --nogit
+ echo 'skip pulling source from git'
+ cd /usr/src/ansible-gpdpocket
+ ANSIBLE_NOCOWS=1
+ ansible-playbook system.yml -e bootstrap=true -v
 [WARNING]: provided hosts list is empty, only localhost is available
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/usr/src/ansible-gpdpocket/roles/audio/tasks/main.yml': line 17, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: create chtrt5645 directory
^ here

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=23   changed=14   unreachable=0    failed=1   
```

**Comment by icebal** [comment] 2017-08-22 04:30
the issue is the following line is missinga space:
 when:ansible_distribution == 'Solus'

**Comment by lucasdurand** [comment] 2017-08-22 04:51
Seems to also be something in:
'/usr/src/ansible-gpdpocket/roles/xorg/tasks/main.yml': line 17, column 1

**Comment by icebal** [comment] 2017-08-22 05:04
its not that line, its the one before. since the space is missing, it registers the next line as invalid, therefore erroring on line 17 instead of 16 :)

**Comment by lucasdurand** [comment] 2017-08-22 05:06
Yes, that's what I meant. Just cp'd the output without thinking. Cheers!

**Comment by cawilliamson** [comment] 2017-08-22 09:50
PR was provided and is now merged. Issue should be resolved. 👍

**Closed** 2017-08-22 09:51 UTC
Labels: bug

**Comment by greg-the-maker** [comment] 2017-08-22 10:14
I'm still getting this error when running gpd-update

> viciouspenguin@Pocket:~$ sudo gpd-update
> [sudo] password for viciouspenguin: 
> waiting for internet connection...
> waiting for apt to be available...
> downloading latest ansible code...
> Fetching origin
> remote: Counting objects: 7, done.
> remote: Compressing objects: 100% (2/2), done.
> remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
> Unpacking objects: 100% (7/7), done.
> From https://github.com/cawilliamson/ansible-gpdpocket
>    76f1c0b..edeef6e  master     -> origin/master
> HEAD is now at edeef6e Merge pull request #99 from icebal/master
> starting ansible playbook...
> Using /usr/src/ansible-gpdpocket/ansible.cfg as config file
>  [WARNING]: provided hosts list is empty, only localhost is available
> 
> ERROR! Syntax Error while loading YAML.
> 
> 
> The error appears to have been in '/usr/src/ansible-gpdpocket/roles/xorg/tasks/main.yml': line 17, column 1, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
> - name: create xorg directories
> ^ here
> 
> viciouspenguin@Pocket:~$

**Comment by Herst** [comment] 2017-08-22 11:37
Maybe in order to prevent such problems in the future a simple script such as the following could be ran as CI:
```sh
find . -type f -name '*.yml' -exec yamllint {} +
```
(https://github.com/adrienverge/yamllint)
