### ISSUE TITLE
failure while trying to remove squashfs working directory

### ISSUE THREAD

**Issue by rdbell** [cawilliamson/ansible-gpdpocket#72] opened 2017-08-19 02:27 UTC
```
TASK [iso : remove squashfs working directory] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "rmtree failed: [Errno 2] No such file or directory: '/var/tmp/bootstrap-iso/squashfs/etc/pacman.d/gnupg/S.gpg-agent.extra'"}

msg: rmtree failed: [Errno 2] No such file or directory: '/var/tmp/bootstrap-iso/squashfs/etc/pacman.d/gnupg/S.gpg-agent.extra'

PLAY RECAP *********************************************************************
localhost                  : ok=36   changed=26   unreachable=0    failed=1 
```
Using the arch-anywhere installer from [https://arch-anywhere.org/](https://arch-anywhere.org/)

**Comment by cawilliamson** [comment] 2017-08-19 09:04
Hi @rdbell 

I have just added changes which may help here (changing default shell) but that error is very strange and I haven't been able to reproduce it.

Could you do the following?

```
reboot # just to be sure nothing is mounted at /var/tmp/bootstrap-iso
rm -rf /var/tmp/bootstrap-iso
```

Then try to run the script again - it should automatically pull the latest code now and should build successfully (it did for me.)

Let me know how it goes.

**Comment by nexus511** [comment] 2017-08-19 10:04
I have seen that issue too. It happens from time to time that things do not get cleanly unmounted (especially when builds fail due to wonky network connections).

It is basically a good advice to run the build-environment in a virtual machine and just reboot it on each build.

**Comment by cawilliamson** [comment] 2017-08-19 10:52
@rdbell I'm going to close this one for now since I cannot reproduce the issue using the same ISO.

If you do continue to have issues after the above instructions though - just reopen it and I'll have another look. :)

**Closed by cawilliamson** 2017-08-19 10:52 UTC
Labels: triage

**Comment by rdbell** [comment] 2017-08-19 21:21
Thanks for the suggestions. I rebooted, recursively removed /var/tmp/bootstrap-iso, re-downloaded the arch-anywhere ISO into the project folder, and then ran `sudo bash bootstrap-iso.sh ./arch-anywhere-2.2.8-x86_64.iso`

The result was the same error:
```
TASK [iso : remove squashfs working directory] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "rmtree failed: [Errno 2] No such file or directory: '/var/tmp/bootstrap-iso/squashfs/etc/pacman.d/gnupg/S.gpg-agent.extra'"}

msg: rmtree failed: [Errno 2] No such file or directory: '/var/tmp/bootstrap-iso/squashfs/etc/pacman.d/gnupg/S.gpg-agent.extra'

PLAY RECAP *********************************************************************
localhost                  : ok=36   changed=25   unreachable=0    failed=1   
```

Here's what's int the /etc/pacman.d/gnupg directory:
```
ronald  ~/g/ansible-gpdpocket (master=) : ls -lha /var/tmp/bootstrap-iso/squashfs/etc/pacman.d/gnupg/
total 1.5M
drwxr-xr-x 3 root root 4.0K Aug 19 14:10 ./
drwxr-xr-x 3 root root 4.0K Aug 19 14:01 ../
-rw-r--r-- 1 root root  114 Aug 19 14:01 gpg.conf
-rw-r--r-- 1 root root    0 Aug 19 14:01 .gpg-v21-migrated
drwx------ 2 root root 4.0K Aug 19 14:01 private-keys-v1.d/
-rw-r--r-- 1 root root 684K Aug 19 14:01 pubring.gpg
-rw-r--r-- 1 root root 684K Aug 19 14:01 pubring.gpg~
-rw------- 1 root root    0 Aug 19 14:01 secring.gpg
-rw-r--r-- 1 root root  48K Aug 19 14:01 tofu.db
-rw-r--r-- 1 root root  13K Aug 19 14:01 trustdb.gpg
```
