### ISSUE TITLE
No battery monitoring on Arch

### ISSUE THREAD

**Issue by jjackzhn** [cawilliamson/ansible-gpdpocket#109] opened 2017-08-24 20:06 UTC
With a fresh install (and bootstrap-system after installation), no battery monitoring information is available.

Arch ISO: 201708
Kernel: 4.13.0-rc0-bootstrap
Bootloader: systemd-boot

**Comment by Herst** [comment] 2017-08-24 21:16
Which BIOS do you have? I ask because the BIOS version with the many option has a bug which required a special workaround in the kernel and therefore didn't work for a long time.

**Comment by jjackzhn** [comment] 2017-08-24 21:23
I have the June 28th version (5.11). It does have many options so it might be the one you are talking about.

**Comment by Herst** [comment] 2017-08-24 21:23
I just noticed that you are on rc0, rc5 would be the current one, if you have a `/usr/src/linux-jwrdegoede` folder, could you please delete it and then re-run `gpd-update`?

**Comment by jjackzhn** [comment] 2017-08-24 21:30
I will try that and report back when it finishes.

**Comment by cawilliamson** [comment] 2017-08-24 22:03
Completely expected behaviour - nothing to worry about.

Will update the README when I get a minute but for now I'm closing this one off - the gpd-update kernel upgrade will resolve this issue. The bootstrap kernel is exactly that - it's not supposed to be kept as your main kernel.

**Closed by cawilliamson** 2017-08-24 22:03 UTC
