### ISSUE TITLE
screen black after log-in after running bootstrap-system.sh

### ISSUE THREAD

**Issue by antichamber** [cawilliamson/ansible-gpdpocket#4] opened 2017-08-06 01:27 UTC
https://youtu.be/hI6-fs6YUCc

**Comment by antichamber** [comment] 2017-08-06 01:58
update https://youtu.be/QuXkMnGDPHA

**Comment by cawilliamson** [comment] 2017-08-06 08:30
Wow, thanks for providing videos - that's utterly awesome and makes my life much easier!

I've just fixed the million and one issues preventing Kali from being boostrapped as an ISO. I'll look in to this now and figure out what the problem is. I think I do actually know what the issue is (modules not being loaded by the initrd - this is now fixed in the ansible playbooks.)

I'll run through a test boot with the ISO and see what happens - either way, we'll get this fixed.

**Comment by cawilliamson** [comment] 2017-08-06 15:11
I believe I have now completely resolved this issue - please try again (either bootstrap-iso or bootstrap-system if you're already installed) and let me know the results.

Again - thanks a lot for the video - it really helped!

Closing this one for now but feel free to re-open if your issue isn't resolved.

**Closed by cawilliamson** 2017-08-06 15:11 UTC
